# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8100:80"
    stdin_open: true
    tty: true